export const INCIDENTS_FETCH_ALL_REQUEST = "INCIDENTS_FETCH_ALL_REQUEST";
export const INCIDENTS_FETCH_ALL_SUCCESS = "INCIDENTS_FETCH_ALL_SUCCESS";
export const INCIDENTS_FETCH_ALL_FAILURE = "INCIDENTS_FETCH_ALL_FAILURE";
export const INCIDENTS_SELECTED = "INCIDENTS_SELECTED";
export const INCIDENTS_APPROVE = "INCIDENTS_APPROVE";
export const INCIDENTS_REJECT = "INCIDENTS_REJECT";
