export const MICROCOPIES_FETCH_ALL_REQUEST = "MICROCOPIES_FETCH_ALL_REQUEST";
export const MICROCOPIES_FETCH_ALL_SUCCESS = "MICROCOPIES_FETCH_ALL_SUCCESS";
export const MICROCOPIES_FETCH_ALL_FAILURE = "MICROCOPIES_FETCH_ALL_FAILURE";
export const SET_MICROCOPY = "SET_MICROCOPY";
