export const AUTH_GET_AUTHURL_REQUEST = 'AUTH_GET_AUTHURL_REQUEST';
export const AUTH_GET_AUTHURL_SUCCESS = 'AUTH_GET_AUTHURL_SUCCESS';
export const AUTH_GET_AUTHURL_FAILURE = 'AUTH_GET_AUTHURL_FAILURE';
export const AUTH_GET_LOGIN_REQUEST = 'AUTH_GET_LOGIN_REQUEST';
export const AUTH_GET_LOGIN_SUCCESS = 'AUTH_GET_LOGIN_SUCCESS';
export const AUTH_GET_LOGIN_FAILURE = 'AUTH_GET_LOGIN_FAILURE';
