export const COUNTIES_FETCH_ALL_REQUEST = 'COUNTIES_FETCH_ALL_REQUEST';
export const COUNTIES_FETCH_ALL_SUCCESS = 'COUNTIES_FETCH_ALL_SUCCESS';
export const COUNTIES_FETCH_ALL_FAILURE = 'COUNTIES_FETCH_ALL_FAILURE';
