export const INCIDENTS_FETCH_ALL_REQUEST = 'INCIDENTS_FETCH_ALL_REQUEST';
export const INCIDENTS_FETCH_ALL_SUCCESS = 'INCIDENTS_FETCH_ALL_SUCCESS';
export const INCIDENTS_FETCH_ALL_FAILURE = 'MARKETS_FETCH_ALL_FAILURE';
